### ISSUE TITLE
Portnout úplně mega důležitý featury z GrillBota

### ISSUE THREAD

**Issue by janch32** [Misha12/Inkluzitron#2]
Hlavně teda:

- [x] peepolove 
- [x] peepoangry

přes to nejede vlak

**Comment by crackonosh** [comment]
V tom pripade se muze portnout i ten `poll`, ne ? Takze udelame new jen vyfikundace, co nevykradem odjinud/nejsou napsane?

**Comment by janch32** [comment]
Afaik `poll` je featura rubbergoda, tak na to kdyžtak udělej novou issue, protože to se bude muset napsat "znovu"
