### ISSUE TITLE
Reply s přílohou někdy(?) odpovídá na uživatele "server" místo původního autora

### ISSUE THREAD

**Issue by janch32** [Misha12/Inkluzitron#40]
Třeba zpráva 
https://discord.com/channels/679717316598038623/837398240604586064/837636687646687262

![image](https://user-images.githubusercontent.com/7803688/116684074-c470d800-a9b0-11eb-901f-67323dddae62.png)

**Comment by Misha12** [comment]
Po několika testech jak přímo v botovi, kdy se nepodařilo situaci vyřešit jsem ještě zkusil udělat požadavky čistě na API (RAW požadavky). 

Bohužel zde nastává stejná situace, pokud volám na Discord API v6. Pokud zavolám na Discord API v8, tak problém nenastává. 

Podle change logu discord API discord sice oficiálně pustil odpovědi (replies) v API v6, nicméně nemá ve v6 plnou podporu. Plná a stabilní podpora pro inline replies je až v API v8. Knihovna Discord.NET s podporou API v8 ještě nevyšla. Dle PR https://github.com/discord-net/Discord.Net/pull/1787 ještě není knihovna připravena pro podporu tohoto API.

Prozatím uzavírám, dokud nebude podpora v8 API v Discord.NET.
