### ISSUE TITLE
Mocking odpovedi (mock)

### ISSUE THREAD

**Issue by crackonosh** [Misha12/Inkluzitron#8]
Pri commandu `mock [text]` by udelal z textu vzdy lower a upper vedle sebe a nasledne poslal mocking spongebob gif

**Comment by janch32** [comment]
Napadlo mě ještě jedno vylepšení - mockovat zprávu jiného uživatele. 
Nejspíš by to mohlo fungovat tak, že by si odpověděl `$mock` na zprávu jiného uživatele. 

Yay or nay?

**Comment by crackonosh** [comment]
> Nejspíš by to mohlo fungovat tak, že by si odpověděl `$mock` na zprávu jiného uživatele.

Chapu to spravne, ze by to bylo jako `$mock [message-link]`?
Podle me cool shit, muzu zatim naimplementovat normalni mocking a pak pridat jeste tohle.

**Comment by janch32** [comment]
Myslel jsem to nějak takhle
![image](https://user-images.githubusercontent.com/7803688/115713827-bac6ef00-a376-11eb-96e6-925001b7f044.png)

**Comment by crackonosh** [comment]
Jo, to by asi taky slo 👍🏻 Teoreticky se potom muzou udelat i oba zpusoby. Mam temer dodelany basic mocking, tak az to budu mit, tak to pushnu do branche a pak nekdy zkusim pospelit ten zbytek.
